name: Deploy DynamoDB Tables

on:
  workflow_dispatch:

env:
  Environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'uat' }}

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your AWS region

      - name: Check Existing DynamoDB Tables
        id: check_tables
        run: |
          echo "Deploying for environment: $Environment"
          ANY_TABLE_MISSING=false
          TABLES=("decoded_vin_${Environment}" "otolane_geopoint_distance_${Environment}" "transport_quote_${Environment}" "vin_req_count_${Environment}")
          echo ${TABLES[@]}
          EXISTING_TABLES=$(aws dynamodb list-tables --query "TableNames" --output json)
          echo ${EXISTING_TABLES[@]}

          for TABLE in "${TABLES[@]}"; do
            if echo "$EXISTING_TABLES" | grep -q "$TABLE"; then
              echo "${TABLE}_EXISTS=true" >> $GITHUB_ENV
            else
              echo "${TABLE}_EXISTS=false" >> $GITHUB_ENV
              ANY_TABLE_MISSING=true >> $GITHUB_ENV
              echo $ANY_TABLE_MISSING
            fi
          done
          echo "ANY_TABLE_MISSING=$ANY_TABLE_MISSING" >> $GITHUB_ENV
          echo "ANY_TABLE_MISSING set to: $ANY_TABLE_MISSING"
      
      - name: Setup DynamoDB table parameters
        run: |
          DecodedVinTableExists=$(printenv "decoded_vin_${Environment}_EXISTS")
          GeoPointDistanceTableExists=$(printenv "otolane_geopoint_distance_${Environment}_EXISTS")
          TransportQuoteTableExists=$(printenv "transport_quote_${Environment}_EXISTS")
          VinReqCountTableExists=$(printenv "vin_req_count_${Environment}_EXISTS")
          echo $DecodedVinTableExists
          echo $GeoPointDistanceTableExists
          echo $TransportQuoteTableExists
          echo $VinReqCountTableExists
      
      - name: Deploy CloudFormation Stack
        if: env.ANY_TABLE_MISSING == 'true'
         aws cloudformation deploy \
            --stack-name dynamodb-tables-${Environment} \
            --template-file workflows/cloudformation.yml \
            --parameter-overrides \
              Environment=${Environment} \
              DecodedVinTableExists=$DecodedVinTableExists \
              GeoPointDistanceTableExists=$GeoPointDistanceTableExists \
              TransportQuoteTableExists=$TransportQuoteTableExists \
              VinReqCountTableExists=$VinReqCountTableExists \
            --capabilities CAPABILITY_NAMED_IAM
