name: Manual Trigger Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - slack

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python and AWS CLI
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        aws-cli: true

    - name: Run AWS Configure
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION

    - name: Check EC2 instance state
      run: |
        instance_state=$(aws ec2 describe-instances --instance-ids i-058320b50ee9e56de --query 'Reservations[*].Instances[*].State.Name' --output text)
        echo "Instance state: $instance_state"
        if [ "$instance_state" = "stopped" ]; then
            echo "EC2 instance is in stopped state. Skipping the workflow."
            echo "::set-output name=skip::true"
        else
            echo "::set-output name=skip::false"
        fi

    - name: Turn on EC2 instance
      if: steps.check_backend_state.outputs.skip == 'true'
      run: |
        aws ec2 start-instances --instance-ids i-0804df08a3b46646c
