name: Manual Trigger Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - slack

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Send Slack notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{'text':'Github actions triggered'}" ${SLACK_WEBHOOK_URL}

    - name: Install Python and AWS CLI
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        aws-cli: true

    - name: Run AWS Configure
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION

    - name: Execute Run Command
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOSTNAME: ${{secrets.IP}}
        USER_NAME: ${{secrets.U_NAME}}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}  '
              ./down.sh
              '

    - name: Turn on EC2 instance
      run: |
        aws ec2 start-instances --instance-ids i-0804df08a3b46646c
