name: Upload a file to S3 bucket

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check the working directory
      run: pwd
    
    - name: Upload file to S3 bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: /home/runner/work/github-actions/github-actions/.github/workflows/
        DEST_DIR: test-folder/
